// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'React',
      collapsible: true,
      collapsed: true,
      items: [
        // "React/index",
        {
          type: 'category',
          label: 'Getting Started',
          items: [{ type: 'autogenerated', dirName: 'React/Getting-Started' }],
        },
        {
          type: 'category',
          label: 'Basics',
          items: [{ type: 'autogenerated', dirName: 'React/Basics' }],
        },
        {
          type: 'category',
          label: 'Communication',
          items: [{ type: 'autogenerated', dirName: 'React/Communication' }],
        },
        {
          type: 'category',
          label: 'Bootstrap',
          items: [{ type: 'autogenerated', dirName: 'React/Bootstrap' }],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [{ type: 'autogenerated', dirName: 'React/Advanced' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Java',
      collapsible: true,
      collapsed: true,
      items: [
        // "Java/index",
        {
          type: 'category',
          label: 'Basics',
          items: [{ type: 'autogenerated', dirName: 'Java/Basics' }],
        },
        {
          type: 'category',
          label: 'OOPS',
          items: [{ type: 'autogenerated', dirName: 'Java/OOPS' }],
        },
        {
          type: 'category',
          label: 'Low Level Designs (LLD)',
          items: [{ type: 'autogenerated', dirName: 'Java/Low-Level-Designs' }],
        },
      ]
    },
    {
      type: 'category',
      label: 'System Design',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'High Level Designs (HLD)',
          items: [{ type: 'autogenerated', dirName: 'System-Design/High-Level-Designs' }],
        },
        {
          type: 'category',
          label: 'Low Level Designs (LLD)',
          items: [{ type: 'autogenerated', dirName: 'System-Design/Low-Level-Designs' }],
        },
      ]
    },
  ],
};

export default sidebars;
